### ISSUE TITLE
Can't disable xtics

### ISSUE THREAD

**Issue by casidiablo** [dkogan/feedgnuplot#24] opened 2016-01-22 04:18 UTC
```
cat /tmp/data | feedgnuplot --terminal 'dumb 100,20' --unset xtics --dump
set terminal dumb 100,20
set grid
unset xtics
set boxwidth 1
histbin(x) = 1 * floor(0.5 + x/1)
set xtics                        <-- it is set again!!!
plot '-'   notitle
1 176
2 135
3 67
4 125
5 82
6 86
7 41
8 145
9 69
10 67
11 40
e
```

**Comment by dkogan** [comment] 2016-01-22 08:11
Thanks. I'll take a look in a bit

**Comment by dkogan** [comment] 2016-01-23 06:59
Hi. Thanks for the report. This was caused by some old code that wasn't useful anymore. I removed it, so the issue is fixed. The fix is committed, but no new release was made yet. I'll do that at some point in the near future. In the meantime, grab the latest master for the fix.

**Closed by dkogan** 2016-01-23 06:59 UTC
