### ISSUE TITLE
Display problems on wayland

### ISSUE THREAD

**Issue by karlkashofer** [dkogan/feedgnuplot#42] opened 2021-02-23 07:50 UTC
Hi !

Just found feedgnuplot via your federated post on planet.debian.org. Very cool tool !

I just noticed some displaying issues in pure wayland:

using X:
`karl@karl-acer2:~$ while true; do < /sys/class/thermal/thermal_zone0/temp awk '{ print $0/1000 }';sleep 1;done | feedgnuplot --stream --with linespoints --exit
Warning: empty y range [51:51], adjusting to [50.49:51.51]
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
`
![X_Bildschirmfoto vom 2021-02-23 08-45-10](https://user-images.githubusercontent.com/10479423/108814926-ed8d7a80-75b3-11eb-9255-704795addf42.png)

`karl@karl-acer2:~$ while true; do < /sys/class/thermal/thermal_zone0/temp awk '{ print $0/1000 }';sleep 1;done | QT_QPA_PLATFORM=wayland feedgnuplot --stream --with linespoints --exit
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Using Wayland-EGL
Using the 'xdg-shell-v6' shell integration
`
![wayland_Bildschirmfoto vom 2021-02-23 08-46-01](https://user-images.githubusercontent.com/10479423/108814955-f9793c80-75b3-11eb-8889-589de003eac7.png)

As you can see the axis labels get messed up, anything you can do about this ?
Cheers,
Karl

**Comment by dkogan** [comment] 2021-02-23 08:04
Yep, that looks messed-up. feedgnuplot doesn't actually make any graphics; rather it asks gnuplot to do that. So the bug (if it is a bug), is in the gnuplot tool.

You can post on the gnuplot bug tracker at https://sourceforge.net/p/gnuplot/bugs/

I'm closing this issue since the problem isn't in this project.

**Closed by dkogan** 2021-02-23 08:04 UTC

**Comment by dkogan** [comment] 2021-02-23 09:38
There's an earlier bug report that may or may not be helpful: https://sourceforge.net/p/gnuplot/bugs/2176/
